This code finds which WNBA players' teams had games on their birthday during the 2023 season.

In [89]:
players <-read.table(file='players.csv', header=TRUE, sep=",")
schedule <-read.table(file='2023schedule.csv', header=TRUE, sep=",")
key <-read.table(file='team_key.csv', header=TRUE, sep=",")

In [90]:
schedule$Date <- strptime(schedule$Date, format = "%a %b %d %Y")
schedule$Date <- format(schedule$Date, format = "%Y-%m-%d")

In [91]:
library(dplyr)

new_df1 <- select(schedule, date = Date, team1 = Visitor.Neutral)

In [92]:
new_df1

    date       team1
1   2023-05-19 Connecticut Sun
2   2023-05-19 Chicago Sky
3   2023-05-19 New York Liberty
4   2023-05-21 Washington Mystics
5   2023-05-21 Chicago Sky
6   2023-05-23 Atlanta Dream
7   2023-05-23 Connecticut Sun
8   2023-05-25 Minnesota Lynx
9   2023-05-26 Dallas Wings
10  2023-05-27 Connecticut Sun
11  2023-05-28 Dallas Wings
12  2023-05-28 Minnesota Lynx
13  2023-05-30 Indiana Fever
14  2023-05-30 New York Liberty
15  2023-06-01 Connecticut Sun
16  2023-06-02 Las Vegas Aces
17  2023-06-02 New York Liberty
18  2023-06-02 Dallas Wings
19  2023-06-03 Seattle Storm
20  2023-06-06 Indiana Fever
21  2023-06-07 Phoenix Mercury
22  2023-06-09 Phoenix Mercury
23  2023-06-09 Chicago Sky
24  2023-06-09 Indiana Fever
25  2023-06-09 Washington Mystics
26  2023-06-11 Connecticut Sun
27  2023-06-11 Dallas Wings
28  2023-06-11 Washington Mystics
29  2023-06-13 Washington Mystics
30  2023-06-13 Seattle Storm
⋮   ⋮          ⋮
147 2023-08-29 Chicago Sky
148 2023-08-29 Minnesota Lynx
149 2023-08-31 Phoenix Mercury
150 2023-08-31 Seattle Storm
151 2023-08-31 Washington Mystics
152 2023-09-01 Dallas Wings
153 2023-09-01 Atlanta Dream
154 2023-09-01 Connecticut Sun
155 2023-09-02 Seattle Storm
156 2023-09-03 New York Liberty
157 2023-09-03 Indiana Fever
158 2023-09-03 Washington Mystics
159 2023-09-03 Phoenix Mercury
160 2023-09-05 Los Angeles Sparks
161 2023-09-05 New York Liberty
162 2023-09-05 Chicago Sky
163 2023-09-05 Washington Mystics
164 2023-09-06 Seattle Storm
165 2023-09-07 Los Angeles Sparks
166 2023-09-08 Minnesota Lynx
167 2023-09-08 Indiana Fever
168 2023-09-08 Seattle Storm
169 2023-09-08 Las Vegas Aces
170 2023-09-08 Atlanta Dream
171 2023-09-10 Dallas Wings
172 2023-09-10 Chicago Sky
173 2023-09-10 Minnesota Lynx
174 2023-09-10 Phoenix Mercury
175 2023-09-10 Washington Mystics
176 2023-09-10 Los Angeles Sparks

In [93]:
new_df2 <- select(schedule, date = Date, team2 = Home.Neutral)

In [94]:
new_df <- bind_rows(new_df1, new_df2) %>%
  mutate(team = ifelse(is.na(team1), team2, team1)) %>%
  select(date, team)
new_df

    date       team
1   2023-05-19 Connecticut Sun
2   2023-05-19 Chicago Sky
3   2023-05-19 New York Liberty
4   2023-05-21 Washington Mystics
5   2023-05-21 Chicago Sky
6   2023-05-23 Atlanta Dream
7   2023-05-23 Connecticut Sun
8   2023-05-25 Minnesota Lynx
9   2023-05-26 Dallas Wings
10  2023-05-27 Connecticut Sun
11  2023-05-28 Dallas Wings
12  2023-05-28 Minnesota Lynx
13  2023-05-30 Indiana Fever
14  2023-05-30 New York Liberty
15  2023-06-01 Connecticut Sun
16  2023-06-02 Las Vegas Aces
17  2023-06-02 New York Liberty
18  2023-06-02 Dallas Wings
19  2023-06-03 Seattle Storm
20  2023-06-06 Indiana Fever
21  2023-06-07 Phoenix Mercury
22  2023-06-09 Phoenix Mercury
23  2023-06-09 Chicago Sky
24  2023-06-09 Indiana Fever
25  2023-06-09 Washington Mystics
26  2023-06-11 Connecticut Sun
27  2023-06-11 Dallas Wings
28  2023-06-11 Washington Mystics
29  2023-06-13 Washington Mystics
30  2023-06-13 Seattle Storm
⋮   ⋮          ⋮
323 2023-08-29 Los Angeles Sparks
324 2023-08-29 Washington Mystics
325 2023-08-31 Connecticut Sun
326 2023-08-31 Los Angeles Sparks
327 2023-08-31 Las Vegas Aces
328 2023-09-01 Indiana Fever
329 2023-09-01 Minnesota Lynx
330 2023-09-01 New York Liberty
331 2023-09-02 Las Vegas Aces
332 2023-09-03 Chicago Sky
333 2023-09-03 Dallas Wings
334 2023-09-03 Los Angeles Sparks
335 2023-09-03 Minnesota Lynx
336 2023-09-05 Connecticut Sun
337 2023-09-05 Dallas Wings
338 2023-09-05 Indiana Fever
339 2023-09-05 Phoenix Mercury
340 2023-09-06 Atlanta Dream
341 2023-09-07 New York Liberty
342 2023-09-08 Chicago Sky
343 2023-09-08 Connecticut Sun
344 2023-09-08 Dallas Wings
345 2023-09-08 Phoenix Mercury
346 2023-09-08 Washington Mystics
347 2023-09-10 Atlanta Dream
348 2023-09-10 Connecticut Sun
349 2023-09-10 Indiana Fever
350 2023-09-10 Las Vegas Aces
351 2023-09-10 New York Liberty
352 2023-09-10 Seattle Storm

In [95]:
joined_df <- left_join(new_df, key, by = "team")
joined_df

    date       team               abb
1   2023-05-19 Connecticut Sun    CON
2   2023-05-19 Chicago Sky        CHI
3   2023-05-19 New York Liberty   NYL
4   2023-05-21 Washington Mystics WSH
5   2023-05-21 Chicago Sky        CHI
6   2023-05-23 Atlanta Dream      ATL
7   2023-05-23 Connecticut Sun    CON
8   2023-05-25 Minnesota Lynx     NA
9   2023-05-26 Dallas Wings       DAL
10  2023-05-27 Connecticut Sun    CON
11  2023-05-28 Dallas Wings       DAL
12  2023-05-28 Minnesota Lynx     NA
13  2023-05-30 Indiana Fever      IND
14  2023-05-30 New York Liberty   NYL
15  2023-06-01 Connecticut Sun    CON
16  2023-06-02 Las Vegas Aces     LVA
17  2023-06-02 New York Liberty   NYL
18  2023-06-02 Dallas Wings       DAL
19  2023-06-03 Seattle Storm      SEA
20  2023-06-06 Indiana Fever      IND
21  2023-06-07 Phoenix Mercury    PHX
22  2023-06-09 Phoenix Mercury    PHX
23  2023-06-09 Chicago Sky        CHI
24  2023-06-09 Indiana Fever      IND
25  2023-06-09 Washington Mystics WSH
26  2023-06-11 Connecticut Sun    CON
27  2023-06-11 Dallas Wings       DAL
28  2023-06-11 Washington Mystics WSH
29  2023-06-13 Washington Mystics WSH
30  2023-06-13 Seattle Storm      SEA
⋮   ⋮          ⋮                  ⋮
323 2023-08-29 Los Angeles Sparks LAS
324 2023-08-29 Washington Mystics WSH
325 2023-08-31 Connecticut Sun    CON
326 2023-08-31 Los Angeles Sparks LAS
327 2023-08-31 Las Vegas Aces     LVA
328 2023-09-01 Indiana Fever      IND
329 2023-09-01 Minnesota Lynx     NA
330 2023-09-01 New York Liberty   NYL
331 2023-09-02 Las Vegas Aces     LVA
332 2023-09-03 Chicago Sky        CHI
333 2023-09-03 Dallas Wings       DAL
334 2023-09-03 Los Angeles Sparks LAS
335 2023-09-03 Minnesota Lynx     NA
336 2023-09-05 Connecticut Sun    CON
337 2023-09-05 Dallas Wings       DAL
338 2023-09-05 Indiana Fever      IND
339 2023-09-05 Phoenix Mercury    PHX
340 2023-09-06 Atlanta Dream      ATL
341 2023-09-07 New York Liberty   NYL
342 2023-09-08 Chicago Sky        CHI
343 2023-09-08 Connecticut Sun    CON
344 2023-09-08 Dallas Wings       DAL
345 2023-09-08 Phoenix Mercury    PHX
346 2023-09-08 Washington Mystics WSH
347 2023-09-10 Atlanta Dream      ATL
348 2023-09-10 Connecticut Sun    CON
349 2023-09-10 Indiana Fever      IND
350 2023-09-10 Las Vegas Aces     LVA
351 2023-09-10 New York Liberty   NYL
352 2023-09-10 Seattle Storm      SEA

In [96]:
joined_df$date <- strftime(joined_df$date, format = "%m-%d")
joined_df

    date  team               abb
1   05-19 Connecticut Sun    CON
2   05-19 Chicago Sky        CHI
3   05-19 New York Liberty   NYL
4   05-21 Washington Mystics WSH
5   05-21 Chicago Sky        CHI
6   05-23 Atlanta Dream      ATL
7   05-23 Connecticut Sun    CON
8   05-25 Minnesota Lynx     NA
9   05-26 Dallas Wings       DAL
10  05-27 Connecticut Sun    CON
11  05-28 Dallas Wings       DAL
12  05-28 Minnesota Lynx     NA
13  05-30 Indiana Fever      IND
14  05-30 New York Liberty   NYL
15  06-01 Connecticut Sun    CON
16  06-02 Las Vegas Aces     LVA
17  06-02 New York Liberty   NYL
18  06-02 Dallas Wings       DAL
19  06-03 Seattle Storm      SEA
20  06-06 Indiana Fever      IND
21  06-07 Phoenix Mercury    PHX
22  06-09 Phoenix Mercury    PHX
23  06-09 Chicago Sky        CHI
24  06-09 Indiana Fever      IND
25  06-09 Washington Mystics WSH
26  06-11 Connecticut Sun    CON
27  06-11 Dallas Wings       DAL
28  06-11 Washington Mystics WSH
29  06-13 Washington Mystics WSH
30  06-13 Seattle Storm      SEA
⋮   ⋮     ⋮                  ⋮
323 08-29 Los Angeles Sparks LAS
324 08-29 Washington Mystics WSH
325 08-31 Connecticut Sun    CON
326 08-31 Los Angeles Sparks LAS
327 08-31 Las Vegas Aces     LVA
328 09-01 Indiana Fever      IND
329 09-01 Minnesota Lynx     NA
330 09-01 New York Liberty   NYL
331 09-02 Las Vegas Aces     LVA
332 09-03 Chicago Sky        CHI
333 09-03 Dallas Wings       DAL
334 09-03 Los Angeles Sparks LAS
335 09-03 Minnesota Lynx     NA
336 09-05 Connecticut Sun    CON
337 09-05 Dallas Wings       DAL
338 09-05 Indiana Fever      IND
339 09-05 Phoenix Mercury    PHX
340 09-06 Atlanta Dream      ATL
341 09-07 New York Liberty   NYL
342 09-08 Chicago Sky        CHI
343 09-08 Connecticut Sun    CON
344 09-08 Dallas Wings       DAL
345 09-08 Phoenix Mercury    PHX
346 09-08 Washington Mystics WSH
347 09-10 Atlanta Dream      ATL
348 09-10 Connecticut Sun    CON
349 09-10 Indiana Fever      IND
350 09-10 Las Vegas Aces     LVA
351 09-10 New York Liberty   NYL
352 09-10 Seattle Storm      SEA

In [97]:
players$DOB <- strftime(players$DOB, format = "%m-%d")
players

    Player               Team Pos Ht   Hometown                Exp Debut DOB
1   Maddy Siegrist       DAL  F                                NA  2023  05-22
2   Lou Lopez Senechal   DAL  DND                              NA  2023  05-12
3   Kadiatou Sissoko     PHX  G                                NA  2023  01-25
4   Sika Kone            CHI  G   5-10                         NA  2023  07-13
5   Kalani Brown         DAL      6-07 Slidell, LA             NA  2019  03-21
6   Diana Taurasi        PHX  G   6-00 Glendale, CA            NA  2006  06-11
7   Candace Parker       LVA  C   6-04 Naperville, IL          NA  2008  04-19
8   Kristi Toliver       WSH  G   5-07 Harrisonburg, VA        NA  2009  01-27
9   Alysha Clark         LVA  G   5-11 Mt. Juliet, TN          NA  2012  07-07
10  DeWanna Bonner       CON  F   6-04 Fairfield, AL           NA  2009  08-21
11  Yvonne Turner        SEA  G   5-10 Omaha, NE               NA  2017  10-13
12  Epiphanny Prince     NYL  G   5-09 Brooklyn, NY            NA  2010  01-11
13  Sami Whitcomb        SEA  G   5-10 Ventura, CA             NA  2017  07-20
14  Shey Peddy           PHX  G   5-07 Roxbury, MA             NA  2019  10-28
15  Courtney Vandersloot NYL  G   5-08 Kent, WA                NA  2011  02-08
16  Cayla George         LVA  F   6-04 Mount Barker, Australia NA  2017  05-01
17  Danielle Robinson    ATL  G   5-09 San Jose, CA            NA  2011  05-10
18  Emma Cannon          IND  F   6-02 Rochester, NY           NA  2017  06-01
19  Sydney Colson        LVA  G   5-08 Houston, TX             NA  2011  08-06
20  Elena Delle Donne    WSH  F   6-05 Wilmington, DE          NA  2013  09-05
21  Tiffany Hayes        CON  G   5-10 Fort Polk, LA           NA  2012  09-20
22  Jasmine Thomas       LAS  G   5-09 Fairfax, VA             NA  2011  09-30
23  Riquna Williams      LVA  DND 5-06 Pahokee, FL             NA  2012  05-28
24  Nneka Ogwumike       LAS  F   6-02 Tomball, TX             NA  2012  07-02
25  Rebekah Gardner      CHI  DND 6-01 Upland, CA              NA  2022  07-09
26  Brittney Griner      PHX  C   6-09 Houston, TX             NA  2013  10-18
27  Tianna Hawkins       WSH  C   6-03 Washington, DC          NA  2013  03-02
28  Layshia Clarendon    LAS  F   5-09 San Bernadino, CA       NA  2013  03-02
29  Erica Wheeler        IND  G   5-07 Miami, FL               NA  2015  05-02
30  Natasha Howard       DAL  F   6-02 Toledo, OH              NA  2014  09-02
⋮   ⋮                    ⋮    ⋮   ⋮    ⋮                       ⋮   ⋮     ⋮
132 Taylor Mikesell      ATL  G   5-10 Massillon, OH           NA  2023  09-30
133 Han Xu               NYL      6-10 Shijiazhuang, China     NA  2019  10-31
134 Victaria Saxton      IND  F   6-02 Rome, GA                NA  2023  11-10
135 Dorka Juhasz         MIN  C   6-05 Pécs, Hungary           NA  2023  12-18
136 Taylor Soule         CHI  F   6-05 Memphis, TN             NA  2023  01-05
137 Jasmine Dickey       DAL  G   5-09 Baltimore, MD           NA  2022  02-23
138 Nyara Sabally        NYL  F   6-05 Berlin, Germany         NA  2023  02-26
139 Kierstan Bell        LVA  F   6-01 Alliance, OH            NA  2022  03-16
140 Ashley Joens         DAL  G   5-10 Melbourne, Australia    NA  2023  03-16
141 Naz Hillmon          ATL  F   6-02 Cleveland, OH           NA  2022  04-05
142 Rhyne Howard         ATL  F   6-02 Chattanooga, TN         NA  2022  04-29
143 Emily Engstler       MIN  F   6-01 New York, NY            NA  2022  05-01
144 Nia Clouden          LAS  G   5-09 Owings Mills, MD        NA  2022  05-17
145 Rae Burrell          LAS  F   6-02 Las Vegas, NV           NA  2022  06-21
146 Queen Egbo           IND  F   6-04 Houston, TX             NA  2022  06-29
147 Veronica Burton      DAL  G   5-09 Newton, MA              NA  2022  07-12
148 Leigha Brown         CON  F   6-01 Auburn, IN              NA  2023  07-14
149 Shakira Austin       WSH  C   6-05 Fredericksburg, VA      NA  2022  07-25
150 NaLyssa Smith        IND  F   6-04 San Antonio, TX         NA  2022  08-08
151 Olivia Nelson-Ododa  CON  F   6-05 Lansing, MI             NA  2022  08-17
152 Liz Dixon            PHX  G   5-10 Melbourne, Australia    NA  2023  09-29
153 Zia Cooke            LAS  G   5-09 Toledo, OH              NA  2023  01-09
154 Diamond Miller       MIN  F   6-03 Montclair, NJ           NA  2023  02-11
155 Jordan Horston       SEA  F   6-02 Dallas, TX              NA  2023  05-21
156 Haley Jones          ATL  F   6-01 Santa Cruz, CA          NA  2023  05-23
157 Laeticia Amihere     ATL  F   6-03 Mississauga, Canada     NA  2023  07-10
158 Iliana Rupert        ATL  F   6-04 Sèvres, France          NA  2022  07-12
159 Awak Kuier           DAL  F   6-04 Cairo, Egypt            NA  2021  08-19
160 Aliyah Boston        IND  C   6-05 U.S. Virgin Islands     NA  2023  12-11
161 Jade Melbourne       SEA  G   5-10 Melbourne, Australia    NA  2023  08-18
    Age G  MPG  PPG  RPG APG
1       32  7.9  3.9 1.7 0.2
2        4  0.0  0.0 0.0 0.0
3       32  6.9  1.1 1.2 0.2
4       16  6.9  2.7 2.2 0.3
5   —   29 15.9  7.7 4.7 0.9
6   41  26 25.2 14.8 3.3 4.4
7   37  19 21.9  8.5 5.1 3.5
8   36  10  8.5  3.5 0.5 0.7
9   36  34 21.7  6.5 3.2 1.0
10  36  34 30.2 18.2 5.6 2.2
11  35  17  9.4  2.5 1.2 0.8
12  35  11  6.1  1.6 0.5 0.7
13  35  33 22.2  9.2 2.8 2.6
14  34  22 11.7  4.0 1.3 1.4
15  34  33 29.3  9.2 3.5 7.9
16  34  27  7.5  2.4 1.6 0.4
17  34  25 18.9  5.6 2.2 3.2
18  34  23  9.8  5.4 3.3 0.5
19  34  23  3.3  0.8 0.3 0.9
20  33  18 25.2 15.5 5.1 2.2
21  33  34 26.9 12.1 3.3 2.6
22  33  26 10.8  2.5 1.1 1.2
23  33   4  0.0  0.0 0.0 0.0
24  33  31 31.0 19.3 9.0 2.8
25  33  16  3.6  1.3 0.7 0.4
26  32  25 26.2 17.2 6.7 2.0
27  32  33 22.8  8.8 5.0 1.5
28  32  19 23.7  8.3 2.7 3.0
29  32  32 25.8 10.0 2.9 5.0
30  31  35 32.5 16.3 8.0 2.3
⋮   ⋮   ⋮  ⋮    ⋮    ⋮   ⋮
132 23   6  4.3  2.8 0.3 0.3
133 23   7  2.4  0.6 0.3 0.0
134 23  11  2.3  1.1 0.6 0.0
135 23  34 21.2  5.3 5.6 2.1
136 23  12  3.0  0.6 0.5 0.2
137 23  15  5.5  1.9 0.7 0.1
138 23  30  7.6  2.3 2.1 0.2
139 23  32 11.5  3.9 1.5 0.4
140 23   8  1.7  0.4 0.2 0.0
141 23  32 12.3  3.6 3.0 0.7
142 23  31 32.4 17.7 4.6 3.3
143 23  12  7.2  1.8 2.4 0.6
144 23  11  5.0  0.7 0.2 0.8
145 23  21  8.7  2.7 1.1 0.4
146 23  15 12.9  5.2 4.5 0.3
147 23  35 13.6  2.3 1.6 2.3
148 23  19  3.3  0.5 0.6 0.3
149 23  17 22.5 10.1 6.9 0.9
150 23  28 23.4 12.5 8.0 1.1
151 23  33 12.6  3.5 3.2 0.6
152 22   9  5.5  2.1 1.1 0.2
153 22  32 13.4  4.6 1.0 0.8
154 22  30 21.5 10.0 3.1 2.4
155 22  31 19.7  6.9 4.6 1.4
156 22  32 15.1  4.3 2.4 2.6
157 22  15  8.1  3.6 1.2 0.2
158 22  13  9.4  2.0 2.8 0.7
159 22  32  9.0  2.1 2.3 0.5
160 21  32 30.4 15.2 8.2 2.0
161 21  24 11.0  3.0 1.3 1.4

In [98]:
matching_rows <- merge(players, joined_df, by.x = c("DOB", "Team"), by.y = c("date", "abb"))
matching_rows

   DOB   Team Player             Pos Ht   Hometown                Exp Debut Age
1  05-23 ATL  Haley Jones        F   6-01 Santa Cruz, CA          NA  2023  22
2  05-28 LVA  Riquna Williams    DND 5-06 Pahokee, FL             NA  2012  33
3  06-11 ATL  Nia Coffey         F   6-01 Saint Paul, MN          NA  2017  28
4  07-07 LVA  Alysha Clark       G   5-11 Mt. Juliet, TN          NA  2012  36
5  07-20 SEA  Sami Whitcomb      G   5-10 Ventura, CA             NA  2017  35
6  07-30 WSH  Ariel Atkins       G   5-08 Dallas, TX              NA  2018  27
7  08-04 WSH  Cyesha Goree       F   6-02 Grand Rapids, MI        NA  2023  30
8  08-06 LVA  Sydney Colson      G   5-08 Houston, TX             NA  2011  34
9  08-08 IND  NaLyssa Smith      F   6-04 San Antonio, TX         NA  2022  23
10 08-08 LVA  A'ja Wilson        F   6-04 Hopkins, SC             NA  2018  27
11 08-10 PHX  Michaela Onyenwere F   6-00 Aurora, CO              NA  2021  24
12 08-13 SEA  Ezi Magbegor       F   6-04 Wellington, New Zealand NA  2020  24
13 08-18 SEA  Jade Melbourne     G   5-10 Melbourne, Australia    NA  2023  21
14 08-22 ATL  Cheyenne Parker    C   6-04 Queens, NY              NA  2015  30
15 08-24 CON  Bernadett Hatar    DND 6-10 Pásztó, Hungary         NA  2021  29
16 08-24 LVA  Kelsey Plum        G   5-08 Poway, CA               NA  2017  29
17 09-05 WSH  Elena Delle Donne  F   6-05 Wilmington, DE          NA  2013  33
18 09-08 IND  Amanda Zahui B     F   6-05 Stockholm, Sweden       NA  2015  29
19 09-10 CHI  Alanna Smith       F   6-04 Hobart, Australia       NA  2019  26
   G  MPG  PPG  RPG APG team
1  32 15.1  4.3 2.4 2.6 Atlanta Dream
2   4  0.0  0.0 0.0 0.0 Las Vegas Aces
3  30 21.5  7.0 4.9 1.6 Atlanta Dream
4  34 21.7  6.5 3.2 1.0 Las Vegas Aces
5  33 22.2  9.2 2.8 2.6 Seattle Storm
6  23 24.7 11.4 3.2 2.3 Washington Mystics
7  10 11.2  3.9 1.2 0.1 Washington Mystics
8  23  3.3  0.8 0.3 0.9 Las Vegas Aces
9  28 23.4 12.5 8.0 1.1 Indiana Fever
10 35 30.2 21.9 9.4 1.7 Las Vegas Aces
11 32 22.2  9.1 3.8 1.4 Phoenix Mercury
12 33 32.0 13.8 7.8 2.4 Seattle Storm
13 24 11.0  3.0 1.3 1.4 Seattle Storm
14 32 25.5 14.2 6.7 1.8 Atlanta Dream
15  6  4.2  1.3 0.7 0.0 Connecticut Sun
16 34 31.7 18.8 2.5 4.4 Las Vegas Aces
17 18 25.2 15.5 5.1 2.2 Washington Mystics
18 12  7.0  1.6 1.3 0.2 Indiana Fever
19 33 27.5 10.1 6.9 1.9 Chicago Sky